language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
matrix:
  fast_finish: true
cache: pip
install:
  - pip install -e .
  - pip install flake8
script:
  - nanodlna list
  - flake8 setup.py nanodlna alternatives
